pipeline {
    agent any
     triggers {
        pollSCM "* * * * *"
     }
    environment {
        GITHUB = credentials('gitHubCredentials')
        registry = "akshaygirpunje/sagan-deploy"
        registryCredential = "dockerHubCredentials"
        dockerImage = " "

    }

    stages {
        stage('Checkout') {
            steps{
                checkout scm
            }
        }
        stage('Build') {
            steps {
                        sh script:'''
                            #!/bin/bash
                            echo "This is start $(pwd)"
                            cd  ./deploy
                            ./gradlew build
                            '''
                        sh script:'''
                           #!/bin/bash
                           echo "This is start $(pwd)"
                           cd ../
                           echo "This is $(pwd)"
                           '''
            }
        }

        stage('Build Docker Image') {

                            steps {
                                echo '=== Building sagan Docker Image ==='
                                script {
                                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                                }
                            }
                }
                stage('Push Docker Image') {
                            steps {
                                echo '=== Pushing sagan Docker Image ==='
                                script {
                                  docker.withRegistry( '', registryCredential ) {
                                       dockerImage.push()
                                          }
                                        }
                            }
                }
                stage('Remove local images') {
                                             steps{
                                             sh "docker rmi $registry:$BUILD_NUMBER"
                                               }
                                                                        }
                stage('Deployment on minikube') {
                                             steps{
                                             sh "whoami"
                                             sh "ssh ubuntu@172.16.10.175 'hostname'"
                                             sh "ssh ubuntu@172.16.10.175 'kubectl get pod'"
                                             sh "ssh ubuntu@172.16.10.175 'kubectl set image Deployment/sagan-spring sagan-spring=akshaygirpunje/sagan-deploy:$BUILD_NUMBER --record'"
                                               }
                                                                        }																		 
																		 
    }
}
