pipeline {
    agent any
     triggers {
        pollSCM "* * * * *"
     }
    environment {
        GITHUB = credentials('gitHubCredentials')
	registry = "akshaygirpunje/sagan-deploy"
        registryCredential = "dockerHubCredentials"
	dockerImage = " "

    }

    stages {
        stage('Checkout') {
            steps{
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'ls -lrth'
                sh 'pwd'
                sh './deploy/gradlew build'
                sh 'cd $WORKSPACE'
            }
        }

        stage('Build Docker Image') {

                            steps {
                                echo '=== Building sagan Docker Image ==='
                                script {
                                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                                }
                            }
                }
                stage('Push Docker Image') {
                            steps {
                                echo '=== Pushing sagan Docker Image ==='
                                script {
			          docker.withRegistry( '', registryCredential ) {
				       dockerImage.push()
				          }
					}
                            }
                }
                stage('Remove local images') {
                                             steps{
                                             sh "docker rmi $registry:$BUILD_NUMBER"
                                               }
									}
    }
}
