pipeline {
    agent any
     triggers {
        pollSCM "* * * * *"
     }
    environment {
        GITHUB = credentials('gitHubCredentials')
	registry = "akshaygirpunje/sagan-deploy"
        registryCredential = "dockerHubCredentials"
	dockerImage = " "

    }

    stages {
        stage('Checkout') {
            steps{
                checkout scm
            }
        }
        stage('Build') {
            steps {
                        sh script:'''
                            #!/bin/bash
                            echo "This is start $(pwd)"
                            cd  ./deploy
                            ./gradlew build                             
                            echo"This is $(pwd)"
                            cd /var/lib/jenkins/workspace/sagan-deploy
                            echo"This is $(pwd)"
                            '''
                //sh 'ls -lrth'
                //sh 'pwd'
                //sh './deploy/gradlew build'
                //sh 'cd $WORKSPACE'
                //sh 'pwd'
            }
        }

        stage('Build Docker Image') {

                            steps {
                                echo '=== Building sagan Docker Image ==='
                                script {
                                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                                }
                            }
                }
                stage('Push Docker Image') {
                            steps {
                                echo '=== Pushing sagan Docker Image ==='
                                script {
			          docker.withRegistry( '', registryCredential ) {
				       dockerImage.push()
				          }
					}
                            }
                }
                stage('Remove local images') {
                                             steps{
                                             sh "docker rmi $registry:$BUILD_NUMBER"
                                               }
									}
    }
}
