---
applications:
- name: springio-renderer
  buildpacks:
  - java_buildpack_offline
  instances: 1
  health-check-type: http
  health-check-http-endpoint: /actuator/health/liveness
  memory: 1024M
  disk_quota: 1024M
  routes:
  - route: springio-renderer.sc2-04-pcf1-apps.oc.vmware.com
  services: